import type { BodyType, FieldGroup, FieldState } from "./types";

export const FIELD_LABELS: Record<
  | "name"
  | "country"
  | "gender"
  | "orientation"
  | "species"
  | "ageGroup"
  | "occupation"
  | "setting"
  | "archetype"
  | "marks"
  | "traits"
  | "plotTwist",
  string
> = {
  name: "Имя",
  country: "Страна",
  gender: "Пол",
  orientation: "Ориентация",
  species: "Вид",
  ageGroup: "Возрастная группа",
  occupation: "Занятие",
  setting: "Сеттинг",
  archetype: "Архетип",
  marks: "Приметы",
  traits: "Характер",
  plotTwist: "Поворот сюжета",
};

export const FIELD_GROUPS: FieldGroup[] = [
  {
    id: "identity",
    title: "Личность",
    fields: ["name", "country", "gender", "orientation", "species", "ageGroup"],
  },
  {
    id: "occupation",
    title: "Занятие",
    fields: ["occupation"],
  },
  {
    id: "world",
    title: "Мир",
    fields: ["setting", "archetype"],
  },
  {
    id: "details",
    title: "Детали",
    fields: ["marks", "traits", "plotTwist"],
  },
];

export const BODY_TYPE_LABELS: Record<BodyType, string> = {
  humanoid: "Гуманоид",
  anthro: "Антро",
  feral: "Ферал",
  monster: "Монстр",
};

export const BODY_TYPE_HINTS: Record<BodyType, string> = {
  humanoid: "Всё, что в целом похоже на человека — включая кентавра",
  anthro: "Антропоморфное животное, рыба, птица, насекомое",
  feral: "Обычное животное по строению тела",
  monster: "Чужое, хтоническое, почти нечеловеческое",
};

export function defaultFieldState(): FieldState {
  return {
    name: { enabled: true, locked: false },
    country: { enabled: true, locked: false },
    gender: { enabled: true, locked: false },
    orientation: { enabled: true, locked: false },
    species: { enabled: true, locked: false },
    ageGroup: { enabled: true, locked: false },
    occupation: { enabled: true, locked: false },
    setting: { enabled: true, locked: false },
    archetype: { enabled: true, locked: false },
    marks: { enabled: true, locked: false },
    traits: { enabled: true, locked: false },
    plotTwist: { enabled: true, locked: false },
  };
}

export const countries = [
  "Россия",
  "Франция",
  "Япония",
  "Бразилия",
  "Норвегия",
  "Египет",
  "США",
  "Индия",
  "Марокко",
  "Корея",
  "Исландия",
  "Мексика",
  "Германия",
  "Таиланд",
  "Австралия",
  "Кения",
  "Аргентина",
  "Швеция",
  "Китай",
  "Италия",
  "Польша",
  "Нигерия",
  "Иран",
  "Канада",
] as const;

export const gendersByBody: Record<BodyType, readonly string[]> = {
  humanoid: [
    "Женщина",
    "Мужчина",
    "Небинарная персона",
    "Гендерфлюид",
    "Агендер",
    "Бигендер",
  ],
  anthro: [
    "Женщина",
    "Мужчина",
    "Небинарная персона",
    "Гендерфлюид",
    "Агендер",
    "Бигендер",
  ],
  feral: ["Самка", "Самец", "Не определяется"],
  monster: ["Женский аспект", "Мужской аспект", "Без пола", "Переменный", "Множественный"],
};

export const ageGroupsByBody: Record<BodyType, readonly string[]> = {
  humanoid: [
    "Ребенок",
    "Подросток",
    "Young adult",
    "Молодой",
    "Средних лет",
    "Зрелый",
    "Пожилой",
    "Старый",
  ],
  anthro: [
    "Ребенок",
    "Подросток",
    "Young adult",
    "Молодой",
    "Средних лет",
    "Зрелый",
    "Пожилой",
    "Старый",
  ],
  feral: ["Детёныш", "Подросток", "Молодой", "Взрослый", "Зрелый", "Старый"],
  monster: ["Новорождённый", "Молодой", "Зрелый", "Древний", "Вне возраста", "Вековой"],
};

export const orientations = [
  "Гетеросексуальность",
  "Гомосексуальность",
  "Бисексуальность",
  "Пансексуальность",
  "Асексуальность",
  "Демисексуальность",
  "Квир",
  "Гетероромантичность",
  "Омнисексуальность",
] as const;

export const orientationsFeral = [
  "Не выражена",
  "Сезонная",
  "Парная",
  "Стаи",
] as const;

export const speciesByBody: Record<BodyType, readonly string[]> = {
  humanoid: [
    "Человек",
    "Эльф",
    "Вампир",
    "Оборотень",
    "Андроид",
    "Фея",
    "Демон",
    "Ангел",
    "Киборг",
    "Дроу",
    "Полуорк",
    "Гном",
    "Русалка",
    "Дух",
    "Тифлинг",
    "Аасимар",
    "Мутант",
    "Кентавр",
  ],
  anthro: [
    "Лис",
    "Волк",
    "Кот",
    "Ворон",
    "Олень",
    "Заяц",
    "Акула",
    "Змея",
    "Пчела",
    "Выдра",
    "Дракон",
    "Ястреб",
    "Рысь",
    "Козёл",
    "Мотылёк",
    "Крокодил",
  ],
  feral: [
    "Лисица",
    "Волк",
    "Рысь",
    "Ворон",
    "Олень",
    "Акула",
    "Змея",
    "Ястреб",
    "Заяц",
    "Медведь",
    "Выдра",
    "Кот",
    "Конь",
    "Сова",
  ],
  monster: [
    "Многоглазый страж",
    "Слизень бездны",
    "Кристаллид",
    "Теневой рой",
    "Хтоническое дитя",
    "Инопланетный скиталец",
    "Костяной левиафан",
    "Шепчущая туманность",
    "Живая геометрия",
    "Пожиратель имён",
  ],
};

export const marksByBody: Record<BodyType, readonly string[]> = {
  humanoid: [
    "Шрам на левой брови",
    "Татуировка в виде змеи",
    "Гетерохромия",
    "Веснушки по всему лицу",
    "Серебряная прядь волос",
    "Шрам на шее",
    "Родинка над губой",
    "Ожог на предплечье",
    "Пирсинг в носу",
    "Тонкий шрам на подбородке",
    "Красные глаза",
    "Тату руны на запястье",
    "Белые волосы",
    "Шрамы на костяшках",
    "Ярко-зелёные глаза",
    "Татуировка звезды за ухом",
  ],
  anthro: [
    "Гетерохромия",
    "Кольцо в ухе",
    "Шрам на морде",
    "Полосатый хвост",
    "Мех с проседью",
    "Пирсинг в брови",
    "Обломанный клык",
    "Ожог на предплечье",
    "Белая отметина на груди",
    "Серебряная прядь гривы",
    "Шрам от когтей на плече",
    "Разный цвет кистей",
    "Кольца на хвосте",
    "Выцветшие подушечки лап",
  ],
  feral: [
    "Порванное ухо",
    "Хромота на передней лапе",
    "Белая отметина на груди",
    "Шрам от когтей",
    "Гетерохромия",
    "Обломанный клык",
    "Седина на морде",
    "Кольцо-метка на лапе",
    "След ожога на боку",
    "Раздвоенный кончик хвоста",
    "Шрам через нос",
    "Редкие светлые перья",
  ],
  monster: [
    "Лишняя челюсть",
    "Глаз на ладони",
    "Неправильная геометрия тени",
    "Свечение трещин в коже",
    "Второй контур, который запаздывает",
    "Щупальце вместо пряди",
    "Руны, которые сами ползут",
    "Пустота вместо зрачка",
    "Костяной гребень",
    "Запах озона и мокрого железа",
    "Дыра, через которую видно звёзды",
    "Шёпот из закрытого рта",
  ],
};

export const settingsByBody: Record<BodyType, readonly string[]> = {
  humanoid: [
    "Киберпанк-мегаполис",
    "Средневековое фэнтези",
    "Постапокалипсис",
    "Космическая станция",
    "Викторианский Лондон",
    "Альтернативные 80-е",
    "Магический реализм современности",
    "Неоготика",
    "Славянское фэнтези",
    "Стимпанк-империя",
    "Холодная война",
    "Античный полис",
  ],
  anthro: [
    "Киберпанк-мегаполис",
    "Средневековое фэнтези",
    "Постапокалипсис",
    "Магический реализм современности",
    "Неоготика",
    "Славянское фэнтези",
    "Пустынный мир",
    "Подводный город",
    "Дальневосточное фэнтези",
    "Стимпанк-империя",
  ],
  feral: [
    "Славянское фэнтези",
    "Пустынный мир",
    "Средневековое фэнтези",
    "Постапокалипсис",
    "Подводный город",
    "Арктическая колония",
    "Магический реализм современности",
    "Дальневосточное фэнтези",
  ],
  monster: [
    "Космическая станция",
    "Постапокалипсис",
    "Неоготика",
    "Подводный город",
    "Пустынный мир",
    "Арктическая колония",
    "Магический реализм современности",
    "Киберпанк-мегаполис",
    "Средневековое фэнтези",
  ],
};

export const occupationRolesByBody: Record<BodyType, readonly string[]> = {
  humanoid: [
    "Лекарь",
    "Охотник",
    "Страж",
    "Шпион",
    "Учёный",
    "Кузнец",
    "Пилот",
    "Жрец",
    "Следопыт",
    "Певец",
    "Вор",
    "Дипломат",
    "Картограф",
    "Медик",
    "Курьер",
    "Архивариус",
    "Детектив",
    "Инженер",
  ],
  anthro: [
    "Лекарь",
    "Охотник",
    "Страж",
    "Шпион",
    "Учёный",
    "Кузнец",
    "Пилот",
    "Жрец",
    "Следопыт",
    "Певец",
    "Вор",
    "Дипломат",
    "Картограф",
    "Медик",
    "Курьер",
    "Инженер",
  ],
  feral: [
    "Вожак",
    "Охотник",
    "Следопыт",
    "Страж",
    "Разведчик",
    "Целитель",
    "Одиночка",
    "Пастырь",
  ],
  monster: [
    "Страж",
    "Вестник",
    "Пожиратель",
    "Хранитель",
    "Скиталец",
    "Шептун",
    "Жнец",
    "Страж порога",
  ],
};

export const occupationTagsByBody: Record<BodyType, readonly string[]> = {
  humanoid: [
    "Выживший",
    "Изгой",
    "Наёмник",
    "Наследник",
    "Беглец",
    "Ученик",
    "Ветеран",
    "Странник",
    "Избранный",
    "Ренегат",
  ],
  anthro: [
    "Выживший",
    "Изгой",
    "Наёмник",
    "Наследник",
    "Беглец",
    "Ученик",
    "Ветеран",
    "Странник",
    "Избранный",
    "Ренегат",
  ],
  feral: [
    "Выживший",
    "Изгой",
    "Раненый",
    "Старейшина",
    "Скиталец",
    "Избранный",
    "Изгнанный",
    "Одинокий",
  ],
  monster: [
    "Бездны",
    "Разлома",
    "Пустоты",
    "Роя",
    "Древних",
    "Порога",
    "Туманности",
    "Костей",
  ],
};

export const archetypesByBody: Record<BodyType, readonly string[]> = {
  humanoid: [
    "Воин",
    "Маг",
    "Странник",
    "Учёный",
    "Интриган",
    "Целитель",
    "Изгой",
    "Тень",
    "Лидер",
    "Мудрец",
    "Бунтарь",
    "Наставник",
    "Трикстер",
    "Хранитель",
    "Романтик",
    "Охотник",
  ],
  anthro: [
    "Воин",
    "Странник",
    "Целитель",
    "Изгой",
    "Тень",
    "Лидер",
    "Бунтарь",
    "Трикстер",
    "Хранитель",
    "Охотник",
    "Мудрец",
    "Романтик",
  ],
  feral: [
    "Вожак",
    "Охотник",
    "Тень",
    "Одиночка",
    "Хранитель",
    "Странник",
    "Трикстер",
    "Страж",
    "Изгой",
  ],
  monster: [
    "Тень",
    "Вестник",
    "Пожиратель",
    "Хранитель",
    "Изгой",
    "Мудрец",
    "Хаос",
    "Страж порога",
    "Искуситель",
  ],
};

export const traits = [
  "Скрытный",
  "Вспыльчивый",
  "Ироничный",
  "Преданный",
  "Циничный",
  "Наивный",
  "Расчётливый",
  "Сострадательный",
  "Гордый",
  "Тревожный",
  "Харизматичный",
  "Упрямый",
  "Молчаливый",
  "Любознательный",
  "Мстительный",
  "Щепетильный",
  "Беспечный",
  "Педантичный",
] as const;

export const plotTwists = [
  "Скрытое прошлое разрушит текущий союз",
  "Придётся предать того, кого любит, чтобы спасти остальных",
  "Сила внутри медленно его уничтожает",
  "Долг перед родом против собственного выбора",
  "Только этот персонаж помнит правду, которую стёрли",
  "Контракт, подписанный в отчаянии, подходит к сроку",
  "Ищет того, кого сам когда-то предал",
  "Маска, без которой мир его не примет, трещит",
  "Нужно выбрать между правдой и чужим спасением",
  "Наследие, от которого нельзя отказаться и нельзя принять",
  "Каждый успех кормит того, кого он ненавидит",
  "Дом, который он защищает, построен на лжи",
  "Время, отпущенное на искупление, почти вышло",
  "То, что казалось проклятием, окажется ключом",
  "Союзник с самого начала был другим лицом",
] as const;

export type NameAtom = { ru: string; en: string };

export type NameCulture = {
  order: "given-family" | "family-given";
  givenF: NameAtom[];
  givenM: NameAtom[];
  givenU: NameAtom[];
  familyAny?: NameAtom[];
  familyF?: NameAtom[];
  familyM?: NameAtom[];
};

const n = (ru: string, en: string): NameAtom => ({ ru, en });

export const namesByCountry: Record<string, NameCulture> = {
  Россия: {
    order: "given-family",
    givenF: [n("Анна", "Anna"), n("Мария", "Maria"), n("Елена", "Elena"), n("Дарья", "Daria"), n("София", "Sofia"), n("Ксения", "Ksenia")],
    givenM: [n("Иван", "Ivan"), n("Алексей", "Alexei"), n("Дмитрий", "Dmitry"), n("Никита", "Nikita"), n("Артём", "Artem"), n("Лев", "Lev")],
    givenU: [n("Саша", "Sasha"), n("Женя", "Zhenya")],
    familyF: [n("Соколова", "Sokolova"), n("Орлова", "Orlova"), n("Волкова", "Volkova"), n("Лебедева", "Lebedeva"), n("Ковалёва", "Kovaleva")],
    familyM: [n("Соколов", "Sokolov"), n("Орлов", "Orlov"), n("Волков", "Volkov"), n("Лебедев", "Lebedev"), n("Ковалёв", "Kovalev")],
  },
  Франция: {
    order: "given-family",
    givenF: [n("Камиль", "Camille"), n("Леа", "Lea"), n("Жюльетт", "Juliette"), n("Манон", "Manon"), n("Элоиза", "Eloise")],
    givenM: [n("Луи", "Louis"), n("Тео", "Theo"), n("Рафаэль", "Raphael"), n("Этьен", "Etienne"), n("Огюст", "Auguste")],
    givenU: [n("Доминик", "Dominique"), n("Клод", "Claude")],
    familyAny: [n("Мартен", "Martin"), n("Дюран", "Durand"), n("Моро", "Moreau"), n("Лефевр", "Lefevre"), n("Руссо", "Rousseau")],
  },
  Япония: {
    order: "family-given",
    givenF: [n("Юки", "Yuki"), n("Аой", "Aoi"), n("Хана", "Hana"), n("Мио", "Mio"), n("Сакура", "Sakura")],
    givenM: [n("Харуто", "Haruto"), n("Рэн", "Ren"), n("Кэнто", "Kento"), n("Сота", "Sota"), n("Харуки", "Haruki")],
    givenU: [n("Хикару", "Hikaru"), n("Аки", "Aki")],
    familyAny: [n("Сато", "Sato"), n("Судзуки", "Suzuki"), n("Такахаси", "Takahashi"), n("Танака", "Tanaka"), n("Ито", "Ito")],
  },
  Бразилия: {
    order: "given-family",
    givenF: [n("Габриэла", "Gabriela"), n("Беатрис", "Beatriz"), n("Лара", "Lara"), n("Изабел", "Isabel"), n("Ана", "Ana")],
    givenM: [n("Тиагу", "Thiago"), n("Лукас", "Lucas"), n("Рафаэл", "Rafael"), n("Педру", "Pedro"), n("Энрике", "Enrique")],
    givenU: [n("Николас", "Nicolas"), n("Алекс", "Alex")],
    familyAny: [n("Силва", "Silva"), n("Сантос", "Santos"), n("Оливейра", "Oliveira"), n("Соуза", "Souza"), n("Кошта", "Costa")],
  },
  Норвегия: {
    order: "given-family",
    givenF: [n("Ингрид", "Ingrid"), n("Фрея", "Freya"), n("Сигрид", "Sigrid"), n("Лив", "Liv"), n("Астрид", "Astrid")],
    givenM: [n("Эрик", "Erik"), n("Магнус", "Magnus"), n("Улав", "Olav"), n("Бьёрн", "Bjorn"), n("Сигурд", "Sigurd")],
    givenU: [n("Ким", "Kim"), n("Элли", "Ellie")],
    familyAny: [n("Хансен", "Hansen"), n("Йохансен", "Johansen"), n("Ульсен", "Olsen"), n("Берг", "Berg"), n("Лунд", "Lund")],
  },
  Египет: {
    order: "given-family",
    givenF: [n("Ясмин", "Yasmin"), n("Нур", "Noor"), n("Фатима", "Fatima"), n("Лейла", "Leila"), n("Сара", "Sara")],
    givenM: [n("Омар", "Omar"), n("Юсуф", "Yusuf"), n("Карим", "Karim"), n("Хасан", "Hassan"), n("Ахмед", "Ahmed")],
    givenU: [n("Нур", "Noor"), n("Изз", "Izz")],
    familyAny: [n("Хасан", "Hassan"), n("Ибрагим", "Ibrahim"), n("Саид", "Said"), n("Фарук", "Farouk"), n("Нагиб", "Naguib")],
  },
  США: {
    order: "given-family",
    givenF: [n("Эйвери", "Avery"), n("Мэй", "Mae"), n("Харпер", "Harper"), n("Элена", "Elena"), n("Джун", "June")],
    givenM: [n("Итан", "Ethan"), n("Калеб", "Caleb"), n("Ной", "Noah"), n("Майлз", "Miles"), n("Джулиан", "Julian")],
    givenU: [n("Ривер", "River"), n("Куинн", "Quinn")],
    familyAny: [n("Рид", "Reed"), n("Беннет", "Bennett"), n("Коул", "Cole"), n("Хейз", "Hayes"), n("Уокер", "Walker")],
  },
  Индия: {
    order: "given-family",
    givenF: [n("Аанья", "Aanya"), n("Прия", "Priya"), n("Иша", "Isha"), n("Меера", "Meera"), n("Дия", "Diya")],
    givenM: [n("Арджун", "Arjun"), n("Вивек", "Vivek"), n("Рохан", "Rohan"), n("Каран", "Karan"), n("Аман", "Aman")],
    givenU: [n("Арья", "Arya"), n("Дев", "Dev")],
    familyAny: [n("Шарма", "Sharma"), n("Патэль", "Patel"), n("Редди", "Reddy"), n("Ийер", "Iyer"), n("Хан", "Khan")],
  },
  Марокко: {
    order: "given-family",
    givenF: [n("Амина", "Amina"), n("Сафия", "Safia"), n("Иман", "Iman"), n("Зайнаб", "Zaynab"), n("Лейла", "Leila")],
    givenM: [n("Юнес", "Younes"), n("Амин", "Amin"), n("Тарик", "Tariq"), n("Рашид", "Rashid"), n("Ильяс", "Ilyas")],
    givenU: [n("Нур", "Noor"), n("Сами", "Sami")],
    familyAny: [n("Белькасем", "Belkacem"), n("Эль-Амини", "El Amini"), n("Беннани", "Bennani"), n("Идрисси", "Idrissi"), n("Шауи", "Chaoui")],
  },
  Корея: {
    order: "family-given",
    givenF: [n("Соён", "Seoyeon"), n("Джиу", "Jiwoo"), n("Хаын", "Haeun"), n("Мина", "Mina"), n("Юна", "Yuna")],
    givenM: [n("Джунхо", "Junho"), n("Минджун", "Minjun"), n("Хёнджин", "Hyunjin"), n("Тэмин", "Taemin"), n("Сонъу", "Seongwoo")],
    givenU: [n("Харин", "Harin"), n("Джимин", "Jimin")],
    familyAny: [n("Ким", "Kim"), n("Ли", "Lee"), n("Пак", "Park"), n("Чон", "Jeong"), n("Чхве", "Choi")],
  },
  Исландия: {
    order: "given-family",
    givenF: [n("Фрейя", "Freyja"), n("Бирта", "Birta"), n("Элин", "Elin"), n("Хельга", "Helga"), n("Уннур", "Unnur")],
    givenM: [n("Эйнар", "Einar"), n("Арнар", "Arnar"), n("Бьёрк", "Bjork"), n("Гуннар", "Gunnar"), n("Олафур", "Olafur")],
    givenU: [n("Алекс", "Alex"), n("Ким", "Kim")],
    familyF: [n("Гудмундсдоттир", "Gudmundsdottir"), n("Йонсдоттир", "Jonsdottir"), n("Эйнарсдоттир", "Einarsdottir"), n("Сигурдсдоттир", "Sigurdsdottir")],
    familyM: [n("Гудмундссон", "Gudmundsson"), n("Йонссон", "Jonsson"), n("Эйнарссон", "Einarsson"), n("Сигурдссон", "Sigurdsson")],
  },
  Мексика: {
    order: "given-family",
    givenF: [n("Лусия", "Lucia"), n("Камила", "Camila"), n("Валентина", "Valentina"), n("Химена", "Jimena"), n("Рената", "Renata")],
    givenM: [n("Матео", "Mateo"), n("Диего", "Diego"), n("Себастьян", "Sebastian"), n("Эмилиано", "Emiliano"), n("Хоакин", "Joaquin")],
    givenU: [n("Алекс", "Alex"), n("Гуадалупе", "Guadalupe")],
    familyAny: [n("Эрнандес", "Hernandez"), n("Гарсия", "Garcia"), n("Мартинес", "Martinez"), n("Лопес", "Lopez"), n("Рамирес", "Ramirez")],
  },
  Германия: {
    order: "given-family",
    givenF: [n("Лена", "Lena"), n("Ханна", "Hanna"), n("Мила", "Mila"), n("Фрида", "Frida"), n("Эмилия", "Emilia")],
    givenM: [n("Лукас", "Lukas"), n("Йонас", "Jonas"), n("Феликс", "Felix"), n("Леон", "Leon"), n("Макс", "Max")],
    givenU: [n("Ким", "Kim"), n("Саша", "Sascha")],
    familyAny: [n("Мюллер", "Muller"), n("Шмидт", "Schmidt"), n("Вебер", "Weber"), n("Фишер", "Fischer"), n("Вагнер", "Wagner")],
  },
  Таиланд: {
    order: "given-family",
    givenF: [n("Налин", "Nalin"), n("Пим", "Pim"), n("Канья", "Kanya"), n("Мали", "Mali"), n("Арин", "Arin")],
    givenM: [n("Киат", "Kiat"), n("Нават", "Nawat"), n("Понг", "Pong"), n("Танак", "Thanak"), n("Чай", "Chai")],
    givenU: [n("Лин", "Lin"), n("Нам", "Nam")],
    familyAny: [n("Срисук", "Srisuk"), n("Вонгчай", "Wongchai"), n("Чайпрасерт", "Chaiprasert"), n("Пханич", "Phanich"), n("Саеттави", "Saettawi")],
  },
  Австралия: {
    order: "given-family",
    givenF: [n("Мэйв", "Maeve"), n("Айла", "Isla"), n("Сьенна", "Sienna"), n("Харпер", "Harper"), n("Мэтти", "Mattie")],
    givenM: [n("Джек", "Jack"), n("Харри", "Harry"), n("Оскар", "Oscar"), n("Лаклан", "Lachlan"), n("Нэш", "Nash")],
    givenU: [n("Ривер", "River"), n("Кейси", "Casey")],
    familyAny: [n("Нг", "Ng"), n("Браун", "Brown"), n("Уилсон", "Wilson"), n("Тейлор", "Taylor"), n("Кларк", "Clark")],
  },
  Кения: {
    order: "given-family",
    givenF: [n("Амина", "Amina"), n("Ванджиру", "Wanjiru"), n("Зари", "Zari"), n("Ньямбира", "Nyambira"), n("Имани", "Imani")],
    givenM: [n("Джабари", "Jabari"), n("Отиено", "Otieno"), n("Камау", "Kamau"), n("Киплигат", "Kiplagat"), n("Муги", "Mugi")],
    givenU: [n("Алекс", "Alex"), n("Сами", "Sami")],
    familyAny: [n("Отиено", "Otieno"), n("Камау", "Kamau"), n("Очиенг", "Ochieng"), n("Кипротич", "Kiprotich"), n("Мванги", "Mwangi")],
  },
  Аргентина: {
    order: "given-family",
    givenF: [n("Соль", "Sol"), n("Эмилия", "Emilia"), n("Каталина", "Catalina"), n("Джульета", "Julieta"), n("Флоренсия", "Florencia")],
    givenM: [n("Бенхамин", "Benjamin"), n("Факундо", "Facundo"), n("Томас", "Tomas"), n("Николас", "Nicolas"), n("Сантьяго", "Santiago")],
    givenU: [n("Алекс", "Alex"), n("Инди", "Indi")],
    familyAny: [n("Гонсалес", "Gonzalez"), n("Родригес", "Rodriguez"), n("Фернандес", "Fernandez"), n("Лопес", "Lopez"), n("Диас", "Diaz")],
  },
  Швеция: {
    order: "given-family",
    givenF: [n("Альва", "Alva"), n("Эбба", "Ebba"), n("Сага", "Saga"), n("Элин", "Elin"), n("Майя", "Maja")],
    givenM: [n("Вильгельм", "Wilhelm"), n("Ноэль", "Noel"), n("Аксель", "Axel"), n("Лиам", "Liam"), n("Элиас", "Elias")],
    givenU: [n("Ким", "Kim"), n("Ловиса", "Lovisa")],
    familyAny: [n("Андерссон", "Andersson"), n("Юханссон", "Johansson"), n("Нильссон", "Nilsson"), n("Линдберг", "Lindberg"), n("Бергстрём", "Bergstrom")],
  },
  Китай: {
    order: "family-given",
    givenF: [n("Мэй", "Mei"), n("Линь", "Lin"), n("Сюэ", "Xue"), n("Янь", "Yan"), n("Цзин", "Jing")],
    givenM: [n("Вэй", "Wei"), n("Хао", "Hao"), n("Цзюнь", "Jun"), n("Чэнь", "Chen"), n("Бо", "Bo")],
    givenU: [n("Юй", "Yu"), n("Хэ", "He")],
    familyAny: [n("Ван", "Wang"), n("Ли", "Li"), n("Чжан", "Zhang"), n("Лю", "Liu"), n("Чэнь", "Chen")],
  },
  Италия: {
    order: "given-family",
    givenF: [n("Джулия", "Giulia"), n("Кьяра", "Chiara"), n("Аврора", "Aurora"), n("Бьянка", "Bianca"), n("Франческа", "Francesca")],
    givenM: [n("Лоренцо", "Lorenzo"), n("Маттео", "Matteo"), n("Леонардо", "Leonardo"), n("Алессандро", "Alessandro"), n("Николо", "Nicolo")],
    givenU: [n("Андреа", "Andrea"), n("Саша", "Sasha")],
    familyAny: [n("Росси", "Rossi"), n("Феррари", "Ferrari"), n("Эспозито", "Esposito"), n("Риччи", "Ricci"), n("Конти", "Conti")],
  },
  Польша: {
    order: "given-family",
    givenF: [n("Зофья", "Zofia"), n("Ханна", "Hanna"), n("Наталия", "Natalia"), n("Мая", "Maja"), n("Лаура", "Laura")],
    givenM: [n("Якуб", "Jakub"), n("Антоний", "Antoni"), n("Шимон", "Szymon"), n("Филип", "Filip"), n("Кацпер", "Kacper")],
    givenU: [n("Алекс", "Alex"), n("Никола", "Nikola")],
    familyF: [n("Новак", "Nowak"), n("Ковальская", "Kowalska"), n("Вишневская", "Wisniewska"), n("Каминская", "Kaminska"), n("Левандовская", "Lewandowska")],
    familyM: [n("Новак", "Nowak"), n("Ковальский", "Kowalski"), n("Вишневский", "Wisniewski"), n("Каминский", "Kaminski"), n("Левандовский", "Lewandowski")],
  },
  Нигерия: {
    order: "given-family",
    givenF: [n("Адаезе", "Adaeze"), n("Чинома", "Chinoma"), n("Фолаке", "Folake"), n("Амина", "Amina"), n("Ифе", "Ife")],
    givenM: [n("Чиди", "Chidi"), n("Олувасеун", "Oluwaseun"), n("Эмека", "Emeka"), n("Тайво", "Taiwo"), n("Ибрагим", "Ibrahim")],
    givenU: [n("Ким", "Kim"), n("Сами", "Sami")],
    familyAny: [n("Окафор", "Okafor"), n("Адебайо", "Adebayo"), n("Балогун", "Balogun"), n("Нваосу", "Nwaosu"), n("Юсуф", "Yusuf")],
  },
  Иран: {
    order: "given-family",
    givenF: [n("Ясмин", "Yasmin"), n("Париса", "Parisa"), n("Лейла", "Leila"), n("Сара", "Sara"), n("Наргис", "Narges")],
    givenM: [n("Реза", "Reza"), n("Каве", "Kaveh"), n("Ариан", "Arian"), n("Нима", "Nima"), n("Хоссейн", "Hossein")],
    givenU: [n("Ника", "Nika"), n("Арьян", "Aryan")],
    familyAny: [n("Хосейни", "Hosseini"), n("Мохаммади", "Mohammadi"), n("Резаи", "Rezaei"), n("Карими", "Karimi"), n("Ахмади", "Ahmadi")],
  },
  Канада: {
    order: "given-family",
    givenF: [n("Элоди", "Elodie"), n("Мэйв", "Maeve"), n("Шарлотта", "Charlotte"), n("Амелия", "Amelia"), n("Ноа", "Noa")],
    givenM: [n("Лиам", "Liam"), n("Тео", "Theo"), n("Этьен", "Etienne"), n("Калеб", "Caleb"), n("Роуэн", "Rowan")],
    givenU: [n("Ривер", "River"), n("Куинн", "Quinn")],
    familyAny: [n("Трамбле", "Tremblay"), n("Рой", "Roy"), n("Ганьон", "Gagnon"), n("Макдональд", "Macdonald"), n("Сингх", "Singh")],
  },
};

export const fallbackCulture: NameCulture = {
  order: "given-family",
  givenF: [n("Ирис", "Iris"), n("Нора", "Nora"), n("Мара", "Mara"), n("Эва", "Eva"), n("Лина", "Lina")],
  givenM: [n("Элиас", "Elias"), n("Роман", "Roman"), n("Кай", "Kai"), n("Нейл", "Neil"), n("Марк", "Mark")],
  givenU: [n("Рен", "Ren"), n("Саша", "Sasha")],
  familyAny: [n("Вейл", "Vale"), n("Кросс", "Cross"), n("Харт", "Hart"), n("Эш", "Ash"), n("Куинн", "Quinn")],
};

export const feralNames: NameAtom[] = [
  n("Серая Грива", "Grey Mane"),
  n("Тихий След", "Quiet Track"),
  n("Рваное Ухо", "Torn Ear"),
  n("Белая Лапа", "White Paw"),
  n("Ночная Река", "Night River"),
  n("Красный Клык", "Red Fang"),
  n("Пепельный Хвост", "Ash Tail"),
  n("Моховой Бок", "Moss Flank"),
  n("Лунный Крик", "Moon Cry"),
  n("Солевой Ветер", "Salt Wind"),
  n("Теневой Шаг", "Shadow Step"),
  n("Янтарная Грива", "Amber Mane"),
];

export const monsterNames: NameAtom[] = [
  n("Ил'харет", "Il'haret"),
  n("Шёпот Бездны", "Abyss Whisper"),
  n("Восьмой Контур", "Eighth Contour"),
  n("Эш-Вара", "Esh-Vara"),
  n("Костяной Гимн", "Bone Hymn"),
  n("Нуль-Имя", "Null-Name"),
  n("Оракул Трещин", "Oracle of Cracks"),
  n("Велум", "Velum"),
  n("Семь Зрачков", "Seven Pupils"),
  n("Холодный Хор", "Cold Choir"),
  n("Ар'кел", "Ar'kel"),
  n("Море-в-Коже", "Sea-in-Skin"),
];
